
version: '2'

services: 

  database:  
    image: hypriot/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: D3dfhB8p3k3F7t7rPhDNCzT7VJFiBaR7Z4shNQLd6YEZwmFxwv
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: Wdnb6EV2x6nNaVuDzeaZ2N9MFbtz3J8YBciz34wkvpkyGT8Apq
    volumes:
      - data:/var/lib/mysql
    ports: 
     - "3306:3306"
    networks:
     - database
 
  snort: 
    build: ./snort
    volumes:
      - ./database/create_mysql:/root/create_mysql
    networks: 
      - database

volumes:
  data:

networks: 
  database:
