version: '2'

services: 

  database:  
    image: hypriot/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: "${ETHERFUSE_ROOT_DB}"
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: "${ETHERFUSE_SNORT_DB}"
    volumes:
      - data:/var/lib/mysql
     #- /tmp/qemu-static/qemu-arm-static:/usr/bin/qemu-arm-static
  
  snort: 
    build: ./snort
    image: etherfuse/snort:0.1
    volumes:
      #- "${QEMU_PATH}:/usr/bin/qemu-arm-static"
      - ./database/create_mysql:/root/create_mysql
    links: 
      - database

  client: 
    build: ./client
    image: etherfuse/client:0.1
    volumes: 
      #- "${QEMU_PATH}:/usr/bin/qemu-arm-static"
      - ./client/app:/usr/src/app
  
volumes:
  data:


