version: '2'

services: 

  database:  
    image: hypriot/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: D3dfhB8p3k3F7t7rPhDNCzT7VJFiBaR7Z4shNQLd6YEZwmFxwv
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: Wdnb6EV2x6nNaVuDzeaZ2N9MFbtz3J8YBciz34wkvpkyGT8Apq
    volumes:
      - data:/var/lib/mysql
     #- /tmp/qemu-static/qemu-arm-static:/usr/bin/qemu-arm-static
  
  snort: 
    build: ./snort
    image: etherfuse/snort:0.1
    volumes:
      #- "${QEMU_PATH}:/usr/bin/qemu-arm-static"
      - ./database/create_mysql:/root/create_mysql
    links: 
      - database
      - test

  test: 
    image: ioft/armhf-debian

  client: 
    build: ./client
    image: etherfuse/client:0.1
    volumes: 
      #- "${QEMU_PATH}:/usr/bin/qemu-arm-static"
      - ./client/app:/usr/src/app
  
volumes:
  data:


