version: '2'

services: 

  database:  
    image: hypriot/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: "${ETHERFUSE_ROOT_DB}"
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: "${ETHERFUSE_SNORT_DB}"
    volumes:
      - data:/var/lib/mysql
      - /tmp/qemu-static/qemu-arm-static:/usr/bin/qemu-arm-static
  
  snort: 
    image: etherfuse/network-visibility 
    volumes:
      - ./snort/snort.conf:/etc/snort/snort.conf
      - ./snort/local.rules:/etc/snort/rules/local.rules
      - ./snort/barnyard2.conf:/etc/snort/barnyard2.conf   
      - "${QEMU_PATH}:/usr/bin/qemu-arm-static"
      - ./database/create_mysql:/root/create_mysql
    links: 
      - database

  client: 
    build: ./client
    image: etherfuse/client:0.0
    volumes: 
      - "${QEMU_PATH}:/usr/bin/qemu-arm-static"
      - ./client/app:/usr/src/app
  
volumes:
  data:


