
version: '2'

services: 

  database:  
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: ${ETHERFUSE_ROOT_DB}
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: ${ETHERFUSE_SNORT_DB}
    volumes:
      - data:/var/lib/mysql
    ports: 
     - "3306:3306"
    networks:
     - database
     - server
 
  # snort: 
  #   build: 
  #     context: ./snort
  #     dockerfile: Dockerfile-Intel
  #   volumes:
  #     - ./database/create_mysql:/root/create_mysql
  #   networks: 
  #     - database

  ping: 
    build: 
      context: ./ping
      dockerfile: Dockerfile-Intel
    volumes_from: 
      - database 
    networks: 
      - database

  # client: 
  #   # build: ./client
  #   image: etherfuse/client:0.1
  #   volumes: 
  #     - ./client/app:/usr/src/app

  # inspector: 
  #   build: 
  #     context: ./inspector
  #     dockerfile: Dockerfile-Intel
  #   network_mode: host
  #   volumes_from: 
  #     - database 

  api:
   build: 
    context: ./api
    dockerfile: Dockerfile-Intel
   volumes_from:
    - database
   networks:
     - server
   ports:
    - "8080:8080"


volumes:
  data:

networks: 
  database:
  server:
