
version: '2'

services: 

  database:  
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: ${ETHERFUSE_ROOT_DB}
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: ${ETHERFUSE_SNORT_DB}
    volumes:
      - data:/var/lib/mysql
    ports: 
     - "3306:3306"
    networks:
     - database
 
  snort: 
    build: 
      context: ./snort
      dockerfile: Dockerfile-Intel
    volumes:
      - ./database/create_mysql:/root/create_mysql
    networks: 
      - database

  ping: 
    build: 
      context: ./ping
      dockerfile: Dockerfile-Intel
    volumes_from: 
      - database 
    networks: 
      - database

volumes:
  data:

networks: 
  database:
