
version: '2'

services: 

  database:  
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: D3dfhB8p3k3F7t7rPhDNCzT7VJFiBaR7Z4shNQLd6YEZwmFxwv
      MYSQL_DATABASE: snort
      MYSQL_USER: snort
      MYSQL_PASSWORD: Wdnb6EV2x6nNaVuDzeaZ2N9MFbtz3J8YBciz34wkvpkyGT8Apq
    volumes:
      - data:/var/lib/mysql
    ports: 
     - "3306:3306"
    networks:
     - database
     - server
 
  snort: 
    build: ./snort
    dockerfile: Dockerfile-Intel
    volumes:
      - ./database/create_mysql:/root/create_mysql
    networks: 
      - database

  ping: 
    build: ./ping
    dockerfile: Dockerfile-Intel
    volumes_from: 
      - database 
    networks: 
      - database

  # client: 
  #   # build: ./client
  #   image: etherfuse/client:0.1
  #   volumes: 
  #     - ./client/app:/usr/src/app

  inspector: 
    build: ./inspector
    dockerfile: Dockerfile-Intel
    network_mode: host
    volumes_from: 
      - database 

  api:
   build: ./api
   dockerfile: Dockerfile-Intel
   volumes_from:
    - database
   networks:
     - server
   ports:
    - "8080:8080"


volumes:
  data:

networks: 
  database:
  server:
